### ISSUE TITLE
Please bring back Checkpoints

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/ilt-practitioner-issues#22]
## Use Case

Checkpoints were a very useful component of the Showoff based course deliveries. The main things they would achieve IMHO were: 

* Provide anonymous feedback to the trainer on how well students are learning, identify opportunities to clarify things, have students assumptions directly challenged
* Help students stay engaged and awake by providing a brief interactive challenge

## Describe the Solution You Would Like

Re-instating the Checkpoints. Either by reviving Showoff or using a similar system (eg https://kahoot.it/ )  

## Describe Alternatives You've Considered

Verbal question and answers could be included in the course, however the problem with that is you usually just get one or two people answering and the rest are left a bit un-invested. Allowing an online quiz system means everyone can participate and learn.

**Comment by josephoaks** [comment]
Showoff is not coming back, please stop asking for it in almost every issue, as a team the decision was made to remove showoff for a number of reasons and this was communicated to the different teams and partners that deliver training.

Showoff checkpoints did not work in Practitioner anymore and have not for at least 2 years due to updates made to showoff. From data shown the more checkpoints students had to do the less answers they gave, this was inconsistent with the idea of checkpoints and few students would use them throughout the course.

That said I do like the concept of checkpoints but not the way there were implemented in showoff. Perhaps making them fun like a game from https:/kahoot.it would get more interests this is something to bring up to the team and get their opinion. Thank you for the suggestion of kahoot.it
