### ISSUE TITLE
Lab 5.2 Windows fails with "There is not enough space on the disk."

### ISSUE THREAD

**Issue by 16c7x** [puppetlabs/ilt-practitioner-issues#57]
## Describe the Bug
If I do a direct copy and paste of the Windows solution and run it I get errors saying disk is out of space. 

## Expected Behavior
It should create the users, home directory and then the Documents/WindowsPowerShell/ directory where it outs the powershell script

## Steps to Reproduce
Test the Windows solution for lab 5.2

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context
I can work around it by adding the following;
```
  file { [ [ $homedir, "${homedir}/Documents", "${homedir}/Documents/WindowsPowerShell" ] ]:
    ensure => directory,
    owner  => $title,
  }
```

I'm not sure how this could ever have worked as Puppet doesn't have the equivalent of a ```mkdir -p``` and each level of a nested directory structure always has to be specified. 
It also appears that ```managehome => true,``` does not work on Windows.

**Comment by martezr** [comment]
The issue is being caused by the SQL server files being downloaded to the Downloads folder for the Administrator account. As part of the sysprep process the default Administrator user account profile is used for the default user profile. This means that when new user accounts are created the SQL server files are being copied to the Downloads folder of each new user account which ultimately results in the instance running out of disk space. The SQL server files are being moved out of the Administrator Downloads directory to prevent the SQL server files from being copied when a new user is created.

**Comment by greglarkin** [comment]
My apologies for introducing that error. @martezr has fixed it, and a new AMI is building now.
